# Can one block of except statements handle multiple exception?

# Yes, a single block of except statements in Python can handle multiple exceptions. 
# try-except blocks can be used to catch and respond to one or multiple exceptions.